name: QuickWaystones
version: '2.3.0'
main: dev.pozzoo.quickwaystones.QuickWaystones
api-version: '1.20'

commands:
  quickWaystones:
    description: Main plugin command
    usage: /quickWaystones <subcommand>